apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deploy
  namespace: coomiix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          command:
            - "/bin/sh"
            - "-c"
            - "exec /opt/keycloak/bin/kc.sh start-dev"
          ports:
            - containerPort: 8080
          env:
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: coomiix-secret
                key: keycloak-admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coomiix-secret
                key: keycloak-admin-password
          - name: KC_DB_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-uri
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: coomiix-secret
                key: postgres-user
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coomiix-secret
                key: postgres-password
          - name: KC_DB
            value: "postgres"
          - name: KC_HOSTNAME
            value: "auth.coomiix.local"
          - name: KC_HOSTNAME_STRICT
            value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: coomiix
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080

